### ISSUE TITLE
Logo Cerit-SP překrývá modal

### ISSUE THREAD

**Issue by allyen** [WebCentrum/UNIweb#10]
Pro zobrazení chyb v případě AJAX requestu používáme modální dialog. Logo CERITu nahoře v záhlaví tento dialog částečně překrývá, asi někde špatně nastavený z-index?

**Comment by sustrradim** [comment]
nehodil bys mi prosím screenshot?

**Comment by allyen** [comment]
![image](https://cloud.githubusercontent.com/assets/1769497/6919010/765e3b24-d7b3-11e4-9db0-cbe6a2bb3c83.png)

**Comment by sustrradim** [comment]
upraveno. snad se mi to podaří Commitnout

**Comment by allyen** [comment]
Funguje :+1:
