### ISSUE TITLE
.above-header-bar

### ISSUE THREAD

**Issue by sustrradim** [WebCentrum/UNIweb#12]
prosím, prosím, v části:

``` html
<div class="row-wide  above-header-bar">
    <div class="row">
            <div class="medium-6  columns  hide-for-small-only">
            <div class="medium-6  columns  hide-for-small-only  text-right">
```

class medium-3 změnit na medium-6 a u dalšího sloupečku y medium-9 na medium-6 taktéž - dochází k přelomení nápisu Masarykova univerzita do dvou řádku a rozbití horní části layoutu.

**Comment by allyen** [comment]
Opravil jsem si u FSS a CERITu
