### ISSUE TITLE
Vyhledávací políčko a vlaječka na mobilech

### ISSUE THREAD

**Issue by allyen** [WebCentrum/UNIweb#7]
V html kódu šablony je sekci nav.main-bar > section umístěno vyhledávací políčko pro mobily a přepínání jazyků, ale nikde se nevykresluje.

**Comment by sustrradim** [comment]
Protože není dostylované a nemám domyšlené správné chování přepínače jazyka :)

**Comment by allyen** [comment]
Jasný, píšu, ať se na to nezapomene a ať máme přehled, co se bude ještě opravovat :)

**Comment by allyen** [comment]
V CERITu už obojí je, tedy uzavírám.
