### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by sustrradim** [WebCentrum/UNIweb#8]
Narazil jsem na problém, kdy jsou za sebou 4 sloupce - náš standardní layout - které pro tablety jdou na půlky, takže vznikne rozložení 2+2 pod sebou. Pokud je druhý sloupec v pořadí nízký, objeví se chyba zalomení a třetí sloupec zůstane viset v pravé části stránky. 
Řešení je vložit za něj clearing v tomto znění:
&lt;div class="clearfix show-for-medium-only"&gt;
&lt;/div&gt;
Ale logiku automatického vkládání nevím - za druhým sloupcem.
Třída show-for-medium-only je zde pro správné zobrazení pouze na tabletech/menším rozlišení.

**Comment by allyen** [comment]
Mělo by to jít, clearfix vložím do vygenerované šablony tehdy, kdy se vyhodnotí, že pro medium se sloupce v řádku zalomí. Zkusím

**Comment by sustrradim** [comment]
OK. Já se podívám, jestli není chybka někde jinde a vyzkouším, jakmile bude čas, různé varianty obsahu a zalamování.

**Comment by allyen** [comment]
Aplikováno, funguje.
